### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by skywalkerlw** [VergeGroup/Verge#160]
You refer `store` object even though it's used only for dispatching action. Does it bring extra performance loss since any change in store will trigger view re-rendering? If yes, what is the good way to minimize this kind of loss?

```swift
struct MyView: View {

  let store: MyStore

  var body: some View {
    UseState(store) { state in
      Text(state.name)
      Button(action: {
        self.store.myAction()
      }) {
        Text("Action")
      }
    }
  }
}
```

**Comment by muukii** [comment]
@swiftyui 

You can specify how you update the UI with.
From that code you pasted, I think the inside code of UseState, actually they need `state.name`.
So, UseState can focus on only updates `name`.

```
UseState(store, .map(\.name)) { name in
  ...
}
```

However, this code might affect the side of deriving the value processing.
Currently, Store updates might cause re-render every time.

**Comment by muukii** [comment]
Ah, I could have an improvement idea that reduces updating UI.
I'll dig in later.

**Comment by skywalkerlw** [comment]
i saw you have something shining merged, and we don't need to worry about performance ,right?
Is there any benchmark test for this improvement?
