### ISSUE TITLE
swift _read yield

### ISSUE THREAD

**Issue by GodL** [VergeGroup/Verge#213]
I see _read yield used in the code 。  Now I'm a little confused what does that mean

**Comment by muukii** [comment]
@GodL 
Hi, thank you.
It's not still an official feature, but  I think it probably increases accessing performance.
It can access and modify directly through _read and _modify.

https://forums.swift.org/t/what-does-collection-subscript-read-do-in-swift-5/20014/6

**Comment by GodL** [comment]
> @GodL
> Hi, thank you.
> It's not still an official feature, but I think it probably increases accessing performance.
> It can access and modify directly through _read and _modify.
> 
> https://forums.swift.org/t/what-does-collection-subscript-read-do-in-swift-5/20014/6

Now I see, but is it ok to use it directly in a production environment??

**Comment by muukii** [comment]
@GodL 
I think there are no serious issues to use it in production.
that features are running in Swift standard library already.
But I would care about what might be significantly changed in the future.
