### ISSUE TITLE
Xcode 13 Compile failed

### ISSUE THREAD

**Issue by Chen-Michael** [VergeGroup/Verge#269]
![截圖 2021-09-27 14 12 22](https://user-images.githubusercontent.com/11660998/134856488-952dd412-0881-4371-8d78-0532cdf8ebb5.png)

Version: 8.8.0

**Comment by ayushP2400** [comment]
hello @Chen-Michael temporary fix is to comment these files as it'll still be functional . I think this is an ongoing feature atm.

**Comment by muukii** [comment]
I guses, this's fixed now
